import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Button from '@mui/material/Button'
import Grid from '@mui/material/Grid';
import Paper from '@mui/material/Paper';
import { styled } from '@mui/material/styles';
import Typography from '@mui/material/Typography';
import { useState } from 'react'
import Box from '@mui/material/Box';
import Container from '@mui/material/Container';
import { width } from '@mui/system'
import SafeHouse from '../components/Areas/SafeHouse'
import UserPanel from '../components/UserPanel'
import Bag from '../components/Bag'

const inter = Inter({ subsets: ['latin'] })

const Item = styled(Paper)(({ theme }) => ({
  backgroundColor: theme.palette.mode === 'dark' ? '#1A2027' : '#fff',
  ...theme.typography.body2,
  padding: theme.spacing(1),
  textAlign: 'center',
  color: theme.palette.text.secondary,
}));

const button = {
  height: '2.5rem'
}

export default function Home() {

  const [area, setArea] = useState<string>()
  const [msgs, setMsgs] = useState<string[]>([])
  const [woods, setWoods] = useState<number>(0)
  const [water, setWater] = useState<number>(0)
  const [berry, setBerry] = useState<number>(0)

  function handleClickArea (area: string) {
    setArea(area)
  }
  function handleClickSleep () {
    setMsgs(pMsgs => [...pMsgs, '你的體力恢復了'])
  }
  function handleClickSearch () {
    const random = Math.random() * 100
    switch (true) {
      case (random >= 0 && random <= 33):
        setWoods(pre => pre + 1)
        setMsgs(pMsgs => [...pMsgs, '得到一塊木頭'])
        break
      case (random >= 34 && random <= 66):
        setWater(pre => pre + 1)
        setMsgs(pMsgs => [...pMsgs, '得到一瓶水'])
        break
      case (random >= 67 && random <= 100):
        setBerry(pre => pre + 1)
        setMsgs(pMsgs => [...pMsgs, '得到一顆樹果'])
        break
      default:
        break
    }
  }

  return (
    <>
      <Head>
        <title>ZombieGo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Grid container spacing={1} sx={{height: '100vh'}}>
          <Grid item xs>
            {msgs && msgs.map((msg, i) => <Item key={i}>{msg}</Item>)}
          </Grid>

          <Grid item xs={6} container direction="column">
            <Box>
              <Button variant="text" onClick={() => handleClickArea('area')}>安全屋</Button>
              <Button variant="text" >未知區域</Button>
            </Box>
            <SafeHouse 
              woods={woods}
              handleClickSleep={handleClickSleep}
              handleClickSearch={handleClickSearch} />
          </Grid>

          <Grid item xs>
            <UserPanel />
            <Bag woods={woods}
            water={water} 
            berry={berry} />
          </Grid>
        </Grid>
      </main>
    </>
  )
}
